#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file support \
    nix-project-org2gfm \
    pkgs.ansifilter \
    pkgs.bash \
    pkgs.coreutils \
    pkgs.direnv \
    pkgs.findutils \
    pkgs.git \
    pkgs.gnugrep \
    pkgs.gnutar \
    pkgs.gzip \
    pkgs.stack \
    pkgs.tree \
    pkgs.which \
    --command \
    org2gfm \
    --ignore links.org \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
