#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep HOME \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nix-project-org2gfm \
    nixpkgs-stable.ansifilter \
    nixpkgs-stable.bash \
    nixpkgs-stable.coreutils \
    nixpkgs-stable.direnv \
    nixpkgs-stable.findutils \
    nixpkgs-stable.git \
    nixpkgs-stable.gnugrep \
    nixpkgs-stable.gnutar \
    nixpkgs-stable.gzip \
    nixpkgs-stable.stack \
    nixpkgs-stable.tree \
    nixpkgs-stable.which \
    --command \
    org2gfm \
    --ignore 'links.org\|home-fake' \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
