# locks the versions of dependencies and GHC
resolver: lts-18.8

# Specifies where the Cabal packages for our project are located.
packages:
- ./library
- ./application

nix:
    packages:
    - icu67

